Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np
#import random

In [26]:
N = 28
y_array = np.arange(N)[::-1]
y_array

array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11,
       10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [50]:
N = 25
z_array = np.arange(0,N,1).reshape(5,5)[::-1]
z_array

array([[20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [58]:
def cross_sum(matrix):
    cross_list = []
    i = 0
    num_strings = len(matrix)
    for any_list in matrix:
        cross_list.append(matrix[i][i])
        i += 1
        if i > num_strings:
            break
    result = sum(cross_list)
    return result

In [59]:
cross_sum(z_array)

60

Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [ ]:
from numpy import linalg

In [83]:
a = np.array( [ [4, 2, 1], [1, 3, 0],[0, 5, 4] ] )
b = np.array( [4, 12,-3] )
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [84]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True